# Generated by Django 5.1.2 on 2024-11-07 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialesInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('stock_inicial', models.IntegerField()),
                ('unidad_medida', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MedidasMaterialesInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HI_NREG', models.IntegerField()),
                ('HI_AUTASE', models.CharField(max_length=255)),
                ('HI_NOMBRE', models.CharField(max_length=255)),
                ('HI_FECNAC', models.DateField()),
                ('HI_UBINAC', models.IntegerField()),
                ('HI_DIRECC', models.CharField(max_length=255)),
                ('HI_SEXO', models.CharField(max_length=255)),
                ('HI_NDOCUM', models.IntegerField()),
                ('HI_ESTCIV', models.CharField(max_length=255)),
                ('HI_CPOLIC', models.CharField(default='valor_por_defecto', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField()),
                ('observacion', models.CharField(max_length=255)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.paciente')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.personal')),
                ('tipo_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.tipoprocedimiento')),
            ],
        ),
        migrations.CreateModel(
            name='CondicionHerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_herida', models.CharField(choices=[('AG', 'Aguda'), ('CR', 'Crónica')], max_length=2)),
                ('complejidad', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4')])),
                ('fase', models.IntegerField(choices=[(1, 'Fase 1'), (2, 'Fase 2'), (3, 'Fase 3')])),
                ('tipo_curacion', models.CharField(choices=[('S', 'Simple'), ('A', 'Avanzada')], max_length=1)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.procedimiento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDiagnosticoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.diagnosticomedico')),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.procedimiento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMaterialesInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('materiales_insumos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.materialesinsumos')),
                ('medidad_materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.medidasmaterialesinsumos')),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.procedimiento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMedicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.medicamentos')),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.procedimiento')),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='tipo_personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico.tipopersonal'),
        ),
    ]
