# Generated by Django 5.1.2 on 2024-11-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0002_personal_dni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleProcedimiento',
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='presion_arterial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='saturacion_oxigeno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='volumen_oxigeno',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
