# Generated by Django 5.1.2 on 2024-11-13 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0004_alter_procedimiento_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimiento',
            name='edad',
        ),
    ]
