# Generated by Django 5.1.2 on 2024-11-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0005_remove_procedimiento_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registromaterialesinsumos',
            name='medidad_materiales',
        ),
        migrations.DeleteModel(
            name='MedidasMaterialesInsumos',
        ),
    ]
