# Generated by Django 5.1.2 on 2024-11-21 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0007_registroprocedimientoespecifico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registromedicamentos',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromedicamentos',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico.paciente'),
        ),
        migrations.AddField(
            model_name='registromedicamentos',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
