# Generated by Django 5.1.2 on 2024-11-22 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0008_registromedicamentos_fecha_registro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registromaterialesinsumos',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromaterialesinsumos',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico.paciente'),
        ),
        migrations.AddField(
            model_name='registromaterialesinsumos',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
