# Generated by Django 5.1.2 on 2024-11-23 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0009_registromaterialesinsumos_fecha_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registromaterialesinsumos',
            name='procedimiento',
        ),
        migrations.RemoveField(
            model_name='registromedicamentos',
            name='procedimiento',
        ),
        migrations.AddField(
            model_name='registromaterialesinsumos',
            name='tipo_procedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico.tipoprocedimiento'),
        ),
        migrations.AddField(
            model_name='registromedicamentos',
            name='tipo_procedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico.tipoprocedimiento'),
        ),
    ]
