# Generated by Django 5.1.2 on 2024-11-25 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0010_remove_registromaterialesinsumos_procedimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProcedimientoEspeciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.CharField(blank=True, max_length=255, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.paciente')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.tipoprocedimiento')),
            ],
        ),
    ]
