# Generated by Django 5.1.2 on 2024-11-26 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0012_registroprocedimientomedicos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrodiagnosticomedico',
            name='procedimiento',
        ),
        migrations.AddField(
            model_name='registrodiagnosticomedico',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='registrodiagnosticomedico',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico.paciente'),
        ),
        migrations.AddField(
            model_name='registrodiagnosticomedico',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrodiagnosticomedico',
            name='tipo_procedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico.tipoprocedimiento'),
        ),
        migrations.AlterField(
            model_name='registrodiagnosticomedico',
            name='diagnostico_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico.diagnosticomedico'),
        ),
        migrations.CreateModel(
            name='RegistroCuracionHerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('xtiempo', models.CharField(blank=True, max_length=255, null=True)),
                ('xcomplejidad', models.CharField(blank=True, max_length=255, null=True)),
                ('fase', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_curacion', models.CharField(blank=True, max_length=255, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.paciente')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.tipoprocedimiento')),
            ],
        ),
        migrations.DeleteModel(
            name='CondicionHerida',
        ),
    ]
