# Generated by Django 5.1.2 on 2024-11-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0013_remove_registrodiagnosticomedico_procedimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialesinsumos',
            name='stock_inicial',
        ),
        migrations.AddField(
            model_name='materialesinsumos',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='materialesinsumos',
            name='fecha_registro',
            field=models.DateField(default='2024-11-26'),
        ),
        migrations.AddField(
            model_name='materialesinsumos',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materialesinsumos',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registromaterialesinsumos',
            name='tipo_movimiento',
            field=models.CharField(blank=True, choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registromaterialesinsumos',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default='2024-11-26'),
            preserve_default=False,
        ),
    ]
