# Generated by Django 5.1.2 on 2024-12-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0014_remove_materialesinsumos_stock_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialesinsumos',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='materialesinsumos',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materialesinsumos',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registromaterialesinsumos',
            name='tipo_movimiento',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], default='entrada', max_length=10),
        ),
    ]
