# Generated by Django 5.1.2 on 2024-12-12 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0015_alter_materialesinsumos_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromedicamentos',
            name='id_procedimiento_especifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico.registroprocedimientoespecifico'),
        ),
    ]
