# Generated by Django 5.1.2 on 2024-12-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0016_registromedicamentos_id_procedimiento_especifico'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromaterialesinsumos',
            name='id_registro_proc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
