# Generated by Django 5.1.2 on 2024-12-12 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0017_registromaterialesinsumos_id_registro_proc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registromaterialesinsumos',
            name='id_registro_proc',
        ),
        migrations.AddField(
            model_name='registromaterialesinsumos',
            name='id_procedimiento_especifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico.registroprocedimientoespecifico'),
        ),
    ]
