# Generated by Django 5.1.2 on 2024-12-12 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0018_remove_registromaterialesinsumos_id_registro_proc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromaterialesinsumos',
            name='id_procedimiento_especifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registromateriales_set', to='topico.registroprocedimientoespecifico'),
        ),
    ]
