# Generated by Django 5.1.2 on 2024-12-12 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0019_alter_registromaterialesinsumos_id_procedimiento_especifico'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiagnosticomedico',
            name='id_procedimiento_curacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico.registrocuracionherida'),
        ),
        migrations.AddField(
            model_name='registromaterialesinsumos',
            name='id_procedimiento_curacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico.registrocuracionherida'),
        ),
        migrations.AddField(
            model_name='registromaterialesinsumos',
            name='id_procedimiento_especiales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico.registroprocedimientoespeciales'),
        ),
        migrations.AddField(
            model_name='registromaterialesinsumos',
            name='id_procedimiento_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico.registroprocedimientomedicos'),
        ),
    ]
