# Generated by Django 5.1.2 on 2025-01-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0020_registrodiagnosticomedico_id_procedimiento_curacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialesinsumos',
            name='stock_inicial',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
