# Generated by Django 5.1.2 on 2025-01-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0021_materialesinsumos_stock_inicial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimiento',
            old_name='fecha_atencion',
            new_name='fecha_registro',
        ),
    ]
