# Generated by Django 5.1.2 on 2025-01-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0022_rename_fecha_atencion_procedimiento_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
