# Generated by Django 5.1.2 on 2025-01-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0023_alter_procedimiento_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='duracion_atencion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='tiempo_registro',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
