# Generated by Django 5.1.2 on 2025-01-08 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0024_procedimiento_duracion_atencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='duracion_atencion',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='tiempo_registro',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
