# Generated by Django 5.1.2 on 2025-01-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0025_alter_procedimiento_duracion_atencion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimiento',
            name='duracion_atencion',
        ),
        migrations.RemoveField(
            model_name='procedimiento',
            name='tiempo_registro',
        ),
    ]
