# Generated by Django 5.1.2 on 2025-01-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0026_remove_procedimiento_duracion_atencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='duracion_atencion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='tiempo_registro',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
