# Generated by Django 5.1.2 on 2025-01-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0029_remove_procedimiento_duracion_atencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
