INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('L.OIDO');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('SUT.');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('EC EXTRÑ.');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('DREN.');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('CAUT');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('URG.');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('OTROS');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('IM');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('SC');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('VIA');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('EV');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('ID');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('P/A');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('TEMPERATURA');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('SAT. OX');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('FC');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('V.O');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('HGT');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('RET. PTO');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('SONDA FOLEY');
INSERT INTO topico_detalleprocedimiento (descripcion) VALUES ('NEBULIZACION');
