INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('1');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('2.0');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('3');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('3.0');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('4.0');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('5');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('6.5');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('7.5');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('10');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('11');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('13');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('14');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('15');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('16');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('18');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('20');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('21');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('22');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('23');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('24');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('25');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('50');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('10X10');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('3X5');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('4X5');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('5X5');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('6X5');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('7X7');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('8X5');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('ADULTO');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('ALGODÓN');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('ELAST. ADHESIVA');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('GX10');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('GX5');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('GX7');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('HIDROCOLOIDE EN GEL');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('HIDROCOLOIDE EXTRAFINO');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('HIDROCOLOIDE GRUESO');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('INTERACTIVO EN GEL');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('PARFINADA');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('PEDIATRICO');
INSERT INTO topico_medidasmaterialesinsumos (descripcion) VALUES ('PLATA IONICA');
