INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('AGUJAS', '2028-05-20', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('APOSITO', '2026-09-18', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('BAJALENGUA', '2026-05-03', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('BAJALG.', '2026-03-05', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('BAND.', '2028-09-20', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('BISTURI', '2026-09-18', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('BSA COLECT.', '2026-05-03', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('CAMPO', '2026-03-05', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('CLNA 9%', '2028-09-20', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('CLNA%', '2028-05-20', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('EQ. CURACION', '2026-09-18', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('EQUIPO. QX', '2026-05-03', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('G.ESTERIL', '2026-03-05', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('G.SIMP', '2028-09-20', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('GASAS', '2028-05-20', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('GUANTE. QX', '2028-09-20', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('GUANTE. SIMP.', '2026-09-18', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('HILO', '2026-05-03', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('HISOP.', '2026-03-05', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('HISOPO', '2028-09-20', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('JERINGAS', '2028-05-20', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('LANC.', '2026-09-18', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('LIDOC.', '2026-05-03', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('LLAVE', '2026-03-05', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('MASCARA', '2028-05-20', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('RIÑON.', '2026-09-18', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('SAB.', '2028-05-20', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('SABANA', '2026-09-18', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('SILVERDIAZINA', '2028-05-20', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('SONDAS', '2028-09-20', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('TIRA', '2029-01-20', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('VENDA', '2026-09-18', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('VENOCLISIS', '2026-05-03', 100, 'UN');
INSERT INTO topico_materialesinsumos (descripcion, fecha_vencimiento, stock_inicial, unidad_medida) VALUES ('VOLUTROL', '2028-09-20', 100, 'UN');
